In [6]:
df = pd.read_csv("Churn_Modelling.csv")

In [7]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [8]:
df.shape

(10000, 14)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [10]:
 df.duplicated().sum()

np.int64(0)

In [11]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [12]:
df["Geography"].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [13]:
df["Gender"].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [14]:
df.drop(columns=["RowNumber","CustomerId","Surname"],inplace = True)

In [15]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [16]:
# # encoding the categorical columns through one hot encoding
# pd.get_dummies(df,columns= ["Geography"	,"Gender"],drop_first=True)

In [17]:
pd.get_dummies(df, columns=["Geography", "Gender"], drop_first=True).astype(int)

CreditScore  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0             619   42       2        0              1          1   
1             608   41       1    83807              1          0   
2             502   42       8   159660              3          1   
3             699   39       1        0              2          0   
4             850   43       2   125510              1          1   
...           ...  ...     ...      ...            ...        ...   
9995          771   39       5        0              2          1   
9996          516   35      10    57369              1          1   
9997          709   36       7        0              1          0   
9998          772   42       3    75075              2          1   
9999          792   28       4   130142              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0                  1           101348       1                  0   
1                  1           112542       0                  0   
2                  0           113931       1                  0   
3                  0            93826       0                  0   
4                  1            79084       0                  0   
...              ...              ...     ...                ...   
9995               0            96270       0                  0   
9996               1           101699       0                  0   
9997               1            42085       1                  0   
9998               0            92888       1                  1   
9999               0            38190       0                  0   

      Geography_Spain  Gender_Male  
0                   0            0  
1                   1            0  
2                   0            0  
3                   0            0  
4                   1            0  
...               ...          ...  
9995                0            1  
9996                0            1  
9997                0            0  
9998                0            1  
9999                0            0  

[10000 rows x 12 columns]

In [18]:
df = pd.get_dummies(df, columns=["Geography", "Gender"], drop_first=True).astype(int)

In [19]:
df

CreditScore  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0             619   42       2        0              1          1   
1             608   41       1    83807              1          0   
2             502   42       8   159660              3          1   
3             699   39       1        0              2          0   
4             850   43       2   125510              1          1   
...           ...  ...     ...      ...            ...        ...   
9995          771   39       5        0              2          1   
9996          516   35      10    57369              1          1   
9997          709   36       7        0              1          0   
9998          772   42       3    75075              2          1   
9999          792   28       4   130142              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0                  1           101348       1                  0   
1                  1           112542       0                  0   
2                  0           113931       1                  0   
3                  0            93826       0                  0   
4                  1            79084       0                  0   
...              ...              ...     ...                ...   
9995               0            96270       0                  0   
9996               1           101699       0                  0   
9997               1            42085       1                  0   
9998               0            92888       1                  1   
9999               0            38190       0                  0   

      Geography_Spain  Gender_Male  
0                   0            0  
1                   1            0  
2                   0            0  
3                   0            0  
4                   1            0  
...               ...          ...  
9995                0            1  
9996                0            1  
9997                0            0  
9998                0            1  
9999                0            0  

[10000 rows x 12 columns]

In [20]:
X = df.drop(columns = ["Exited"]) #input cols
y = df["Exited"] # output cols
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size= 0.2,random_state = 1)

In [21]:
X_train

CreditScore  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
2694          628   29       3   113146              2          0   
5140          626   29       4   105767              2          0   
2568          612   47       6   130024              1          1   
3671          646   52       6   111739              2          0   
7427          714   33       8   122017              1          0   
...           ...  ...     ...      ...            ...        ...   
2895          621   47       7   107363              1          1   
7813          684   63       3    81245              1          1   
905           672   45       9        0              1          1   
5192          663   39       8        0              2          1   
235           763   42       6   100160              1          1   

      IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
2694               1           124749                  1                0   
5140               0            41104                  0                0   
2568               1            45750                  1                0   
3671               1            68367                  1                0   
7427               0           162515                  0                1   
...              ...              ...                ...              ...   
2895               1            66799                  1                0   
7813               0            69643                  1                0   
905                1            92027                  0                0   
5192               1           101168                  0                0   
235                0            33462                  1                0   

      Gender_Male  
2694            1  
5140            0  
2568            0  
3671            0  
7427            1  
...           ...  
2895            1  
7813            0  
905             0  
5192            0  
235             1  

[8000 rows x 11 columns]

In [22]:
y_test

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [23]:
X_train.shape

(8000, 11)

# Scaling the Data
Data scaling is essential in many scenarios to ensure that your machine learning models or statistical analyses work effectively and yield accurate results. The goal is to adjust the values of features so they have comparable ranges, making the computations more efficient and meaningful.
Why Do We Need It?
- Feature Comparison: In datasets, features often have varying scales. For example, age might range from 0 to 100, while income could be in thousands or millions. Without scaling, algorithms can give undue importance to larger values.
- Improve Model Performance: Many machine learning algorithms (like gradient descent-based models, SVMs, or k-means clustering) are sensitive to feature magnitudes. Scaling ensures these algorithms converge faster and perform better.
- Prevent Bias: Unscaled data can introduce bias, especially in algorithms that calculate distances (like k-nearest neighbors or PCA). A feature with larger values might dominate, undermining others.
- Optimize Neural Networks: When training neural networks, scaled inputs help the model learn more efficiently by avoiding unstable gradients.
- Normalization Across Features: Scaled data improves interpretability, especially when comparing coefficients in linear regression.




In [24]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


1. **Importing StandardScaler**:
   - The `StandardScaler` applies standardization to your data by removing the mean and scaling to unit variance (i.e., making the mean 0 and the standard deviation 1).

2. **Creating the Scaler Object**:
   ```python
   scaler = StandardScaler()
   ```
   - This initializes the scaler. No transformation happens yet; it's just preparing the tool.

3. **Scaling the Training Data**:
   ```python
   X_train_scaled = scaler.fit_transform(X_train)
   ```
   - The `fit_transform` method performs two operations:
     - **Fit:** Calculates the mean and standard deviation of `X_train` (training data).
     - **Transform:** Uses these calculated values to standardize the training data.

4. **Scaling the Test Data**:
   ```python
   X_test_scaled = scaler.transform(X_test)
   ```
   - The `transform` method applies the scaling parameters (mean and standard deviation) calculated during `fit` on the training data to the test data. **Note:** You don’t use `fit_transform` here because you don’t want to recompute the scaling parameters from the test data—it ensures consistency.

### Why is this approach important?
Separating the scaling process for training and test data (i.e., fitting only on `X_train`) avoids **data leakage**, ensuring your test data remains truly unseen during training. This is critical for building reliable machine learning models.

Let me know if you'd like a more detailed walkthrough or assistance with implementing this!

Recomputing scaling parameters on the test data would essentially allow the test data to influence the scaling process, which could lead to **data leakage**. Data leakage occurs when information from the test data, which is meant to simulate unseen data, is inadvertently used in the training process. This undermines the purpose of having a separate test set and can result in overly optimistic model performance metrics.

By using only `transform` on the test set, you ensure that the scaling is based solely on the training data, maintaining the integrity of the evaluation process. This is a critical step in creating reliable and fair machine learning models.

Would you like a deeper dive into other best practices for avoiding data leakage or improving model evaluation?

In [25]:
X_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [26]:
X_test_scaled

array([[-1.03768121,  0.77498705, -1.0482813 , ..., -0.58312392,
        -0.57273139,  0.91509065],
       [ 0.30708683, -0.46686456, -0.70174202, ..., -0.58312392,
        -0.57273139,  0.91509065],
       [-1.23422423,  0.29735181, -1.0482813 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       ...,
       [-0.86182692, -0.46686456,  1.72403288, ..., -0.58312392,
         1.74601919,  0.91509065],
       [-0.30323097, -0.84897275, -1.0482813 , ...,  1.71490137,
        -0.57273139, -1.09278791],
       [ 0.04847759,  1.25262228,  1.3774936 , ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [27]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [28]:
model = Sequential()

model.add(Dense(3,activation = "sigmoid",input_dim = 11))
model.add(Dense(1,activation = "sigmoid")) #output layer

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [29]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 3)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
#model Compilation

In [31]:
model.compile(loss="binary_crossentropy", optimizer = "Adam")

In [32]:
model.fit(X_train_scaled,y_train,epochs=10,verbose =1)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.7540
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.5839
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5083
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4749
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4651
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4559
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4322
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4371
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4414
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4329


what does verbose do ?


The verbose parameter controls the amount of information displayed during the training process of your machine learning model. It essentially determines how "talkative" the training process will be. Here's a breakdown of the common values for verbose:

verbose=0: This is the silent mode. The training process will run without displaying any progress or information to the console. It's useful when you want to train models in the background or as part of a larger script without cluttering the output.

verbose=1: This is the progress bar mode. It displays a progress bar indicating the progress of each epoch during training. You'll typically see information about the loss and metrics (e.g., accuracy) for each epoch. This is the default setting in many machine learning libraries and is helpful for monitoring training progress

verbose=2: This is the one line per epoch mode. It prints a single line of information for each epoch, showing the epoch number, loss, and metrics. It provides less visual feedback than the progress bar but can be useful for logging training details in a more concise format.

In simpler terms:

Think of verbose as a control for how much your model wants to tell you about what it's doing while it's learning.

verbose=0: The model is completely silent and doesn't give you any updates.
verbose=1: The model shows you a progress bar, like a loading bar on a website, so you can see how far along it is in the training process.
verbose=2: The model gives you a short update after each round of learning, telling you how well it's doing.

In [33]:
# our weigts and biases of layer-0

model.layers[0].get_weights()

[array([[ 0.04886125, -0.2539421 , -0.13790405],
        [-2.2053704 ,  0.5958595 , -0.94701266],
        [-0.03366099, -0.01749655,  0.14704284],
        [-0.3412356 ,  0.16180424, -0.55262333],
        [ 0.18896905,  0.11173173,  0.13492697],
        [-0.1407268 , -0.46876636, -0.09185725],
        [ 0.4672746 , -1.0674841 ,  0.96910405],
        [-0.12370457,  0.08465984,  0.18810773],
        [-0.33313093,  0.9598573 , -0.28876176],
        [ 0.1526628 , -0.11273116, -0.330232  ],
        [ 0.3505755 , -0.38567457,  0.7743214 ]], dtype=float32),
 array([ 0.694489  , -0.50340456,  0.26087436], dtype=float32)]

# layer 0 :- 33 weights + 3 biases

# layer 1 :- 3 weights + 1 bias

In [34]:
# weight and biases of layer -1
model.layers[1].get_weights()

[array([[-1.4855801 ],
        [ 0.74394435],
        [-0.58999705]], dtype=float32),
 array([-0.6242758], dtype=float32)]

In [35]:
model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[0.12541914],
       [0.1425206 ],
       [0.13010016],
       ...,
       [0.07222158],
       [0.1291549 ],
       [0.3615633 ]], dtype=float32)

# the problem is the model output is not 1 or 0 because you are using sigmoid whose output is a probability .

#  So ,we just need to decide a threshold value

In [36]:
 y_log = model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [37]:
y_pred = np.where(y_log>0.5, 1 ,0)

In [38]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8045